### ISSUE TITLE
HTTP 500 on GET index.php

### ISSUE THREAD

**Issue by Klischeepunk** [justinwalsh/daux.io#382]
[Thu Jun 23 12:20:09.311638 2016] [:error] [pid 26366] [client SOME] PHP Fatal error:  
Uncaught Error: Function name must be a string in $WEB_DIR/vendor/erusev/parsedown/Parsedown.php:895\n
Stack trace:\n#0 $WEB_DIR/vendor/erusev/parsedown/Parsedown.php(932): 
Parsedown->element(Array)\n
#1 $WEB_DIR/vendor/erusev/parsedown/Parsedown.php(258):
 Parsedown->elements(Array)\n
#2 $WEB_DIR/vendor/erusev/parsedown/Parsedown.php(49):
 Parsedown->lines(Array)\n
#3 $WEB_DIR/libs/daux_page.php(191): 
 Parsedown->text('Dieses Handbuch...')\n
#4 $WEB_DIR/libs/daux_page.php(156): 
 Todaymade\\Daux\\MarkdownPage->generate_page()\n
#5 $WEB_DIR/libs/daux_page.php(27):
 Todaymade\\Daux\\MarkdownPage->get_page_content()\n
#6 $WEB_DIR/index.php(70): Todaymade\\Daux\\SimplePage->display()\n
#7 {main}\n  
 thrown in $WEB_DIR/vendor/erusev/parsedown/Parsedown.php on line 895

php is already the newest version (1:7.0+42). (<- relevant)
apache 2
linux debian

Fix: 
Old Line 895 Parsedown.php:895
       `$markup .= $this->$Element['handler']($Element['text']);`

New Line 895 Parsedown.php:895
 `$markup .= $this->{$Element['handler']}($Element['text']);`

**Comment by Klischeepunk** [comment]
Okay, my coworker told me the version he used is out of date - thanks :) Sorry for this, can be closed.
